### ISSUE TITLE
vmLog does not display output for an Event with only a string.

### ISSUE THREAD

**Issue by weserickson** [vitelabs/soliditypp#3]
The vmLog does not display output for an Event with only a string.

Here's a quick example of the issue:
```
pragma soliditypp ^0.4.3;

contract EventStringBug {
    
    // Bug: events with only a string value do not display string data in vmLog on debug console.
    event BrokenEvent(string mystring);
    onMessage EmitBrokenEvent(){
        emit BrokenEvent("Event emitted!");
    }

    // However, if an address is also present, the string displays properly.
    event WorkingEvent(address myaddress, string mystring);
    onMessage EmitWorkingEvent(){
        emit WorkingEvent(msg.sender, "Event emitted!");
    }

}
```

Broken event output, does not display "Event Emitted!" in log:
![Screen Shot 2021-08-11 at 11 29 16 AM](https://user-images.githubusercontent.com/68757948/129083561-775a293e-48a6-4b87-8d59-5fff36250124.png)

Working event output:
![Screen Shot 2021-08-11 at 11 29 09 AM](https://user-images.githubusercontent.com/68757948/129083550-5040d40c-7b00-43e4-97cd-50dfa979af97.png)

Using VSCode Soliditypp extension, v0.7.7, on macOS 10.15.7.

**Comment by charles-liu** [comment]
It's a vite.js issue: https://github.com/vitelabs/vite.js/issues/48 and fixed in 2.3.17.
